export const destinations = [
    { name: "Agra Taxi service", url: "/best-outstation-cab-in-agra-one-way-round-trip-taxi-service-agra/", pickup: "Agra", drop: "Agra" },
    { name: "Agra to Ayodhya Cab", url: "/agra-to-ayodhya-cab/", pickup: "Agra", drop: "Ayodhya" },
    { name: "Agra to Banbasa Cab", url: "/agra-to-banbasa-cab/", pickup: "Agra", drop: "Banbasa" },
    { name: "Agra to Bareilly Cab", url: "/agra-to-bareilly-cab/", pickup: "Agra", drop: "Bareilly" },
    { name: "Agra to Dehradun Cab", url: "/agra-to-dehradun-cab/", pickup: "Agra", drop: "Dehradun" },
    { name: "Agra to Delhi Airport Cab", url: "/agra-to-delhi-airport-cab/", pickup: "Agra", drop: "Delhi Airport" },
    { name: "Agra to Ghaziabad Cab", url: "/agra-to-ghaziabad-cab/", pickup: "Agra", drop: "Ghaziabad" },
    { name: "Agra to Gorakhpur Cab", url: "/agra-to-gorakhpur-cab/", pickup: "Agra", drop: "Gorakhpur" },
    { name: "Agra to Gwalior Cab", url: "/agra-to-gwalior-cab/", pickup: "Agra", drop: "Gwalior" },
    { name: "Agra to Haldwani Cab", url: "/agra-to-haldwani-cab/", pickup: "Agra", drop: "Haldwani" },
    { name: "Agra to Haridwar Cab", url: "/agra-to-haridwar-cab/", pickup: "Agra", drop: "Haridwar" },
    { name: "Agra to Jaipur Cab", url: "/agra-to-jaipur-cab/", pickup: "Agra", drop: "Jaipur" },
    { name: "Agra to Kainchi dham Cab", url: "/agra-to-kainchi-dham-cab/", pickup: "Agra", drop: "Kainchi dham" },
    { name: "Agra to Kanpur Cab", url: "/agra-to-kanpur-cab/", pickup: "Agra", drop: "Kanpur" },
    { name: "Agra to Khatoo Cab", url: "/agra-to-khatoo-cab/", pickup: "Agra", drop: "Khatoo" },
    { name: "Agra to Lucknow Cab", url: "/agra-to-lucknow-cab/", pickup: "Agra", drop: "Lucknow" },
    { name: "Agra to Manona dham Cab", url: "/agra-to-manona-dham-cab/", pickup: "Agra", drop: "Manona dham" },
    { name: "Agra to Meerut Cab", url: "/agra-to-meerut-cab/", pickup: "Agra", drop: "Meerut" },
    { name: "Agra to Moradabad Cab", url: "/agra-to-moradabad-cab/", pickup: "Agra", drop: "Moradabad" },
    { name: "Agra to Mumbai Cab", url: "/agra-to-mumbai-cab/", pickup: "Agra", drop: "Mumbai" },
    { name: "Agra to Nainital Cab", url: "/agra-to-nainital-cab/", pickup: "Agra", drop: "Nainital" },
    { name: "Agra to Noida Cab", url: "/agra-to-noida-cab/", pickup: "Agra", drop: "Noida" },
    { name: "Agra to Prayagraj Cab", url: "/agra-to-prayagraj-cab", pickup: "Agra", drop: "Prayagraj" },
    { name: "Agra to Rampur Cab", url: "/agra-to-rampur-cab", pickup: "Agra", drop: "Rampur" },
    { name: "Agra to Rudrapur Cab", url: "/agra-to-rudrapur-cab", pickup: "Agra", drop: "Rudrapur" },
    { name: "Agra Tour Packages", url: "/agra-tour", pickup: "Agra", drop: "Tour Package" },
    { name: "Aligarh Taxi Service", url: "/taxi-service-in-aligarh", pickup: "Aligarh", drop: "Service Area" },
    { name: "Aligarh to Agra Cab", url: "/aligarh-to-agra-cab", pickup: "Aligarh", drop: "Agra" },
    { name: "Aligarh to Ayodhya Cab", url: "/aligarh-to-ayodhya-cab", pickup: "Aligarh", drop: "Ayodhya" },
    { name: "Aligarh to Bareilly Cab", url: "/aligarh-to-bareilly-cab", pickup: "Aligarh", drop: "Bareilly" },
    { name: "Aligarh to Chandigarh Cab", url: "/aligarh-to-chandigarh-cab", pickup: "Aligarh", drop: "Chandigarh" },
    { name: "Aligarh to Dehradun Cab", url: "/aligarh-to-dehradun-cab", pickup: "Aligarh", drop: "Dehradun" },
    { name: "Aligarh to Delhi Cab", url: "/aligarh-to-delhi-cab", pickup: "Aligarh", drop: "Delhi" },
    { name: "Aligarh to Faridabad Cab", url: "/aligarh-to-faridabad-cab", pickup: "Aligarh", drop: "Faridabad" },
    { name: "Aligarh to Ghaziabad Cab", url: "/aligarh-to-ghaziabad-cab", pickup: "Aligarh", drop: "Ghaziabad" },
    { name: "Aligarh to Gurgaon Cab", url: "/aligarh-to-gurgaon-cab", pickup: "Aligarh", drop: "Gurgaon" },
    { name: "Aligarh to Haldwani Cab", url: "/aligarh-to-haldwani-cab", pickup: "Aligarh", drop: "Haldwani" },
    { name: "Aligarh to Haridwar Cab", url: "/aligarh-to-haridwar-cab", pickup: "Aligarh", drop: "Haridwar" },
    { name: "Aligarh to Jaipur Cab", url: "/aligarh-to-jaipur-cab", pickup: "Aligarh", drop: "Jaipur" },
    { name: "Aligarh to Kainchi Dham Cab", url: "/aligarh-to-kainchi-dham-cab", pickup: "Aligarh", drop: "Kainchi Dham" },
    { name: "Aligarh to Kanpur Cab", url: "/aligarh-to-kanpur-cab", pickup: "Aligarh", drop: "Kanpur" },
    { name: "Aligarh to Lucknow Cab", url: "/aligarh-to-lucknow-cab", pickup: "Aligarh", drop: "Lucknow" },
    { name: "Aligarh to Manona Dham Cab", url: "/aligarh-to-manona-dham-cab", pickup: "Aligarh", drop: "Manona Dham" },
    { name: "Aligarh to Mathura Cab", url: "/aligarh-to-mathura-cab", pickup: "Aligarh", drop: "Mathura" },
    { name: "Aligarh to Meerut Cab", url: "/aligarh-to-meerut-cab", pickup: "Aligarh", drop: "Meerut" },
    { name: "Aligarh to Moradabad Cab", url: "/aligarh-to-moradabad-cab", pickup: "Aligarh", drop: "Moradabad" },
    { name: "Aligarh to Mussoorie Cab", url: "/aligarh-to-mussoorie-cab", pickup: "Aligarh", drop: "Mussoorie" },
    { name: "Aligarh to Nainital Cab", url: "/aligarh-to-nainital-cab", pickup: "Aligarh", drop: "Nainital" },
    { name: "Aligarh to Noida Cab", url: "/aligarh-to-noida-cab", pickup: "Aligarh", drop: "Noida" },
    { name: "Almora to Bareilly Cab", url: "/almora-to-bareilly-cab", pickup: "Almora", drop: "Bareilly" },
    { name: "Almora to Kainchi Dham Cab", url: "/almora-to-kainchi-dham-cab", pickup: "Almora", drop: "Kainchi Dham" },
    { name: "Almora to Manona Dham Cab", url: "/almora-to-manona-dham-cab", pickup: "Almora", drop: "Manona Dham" },
    { name: "Amroha to Bareilly Cab", url: "/amroha-to-bareilly-cab", pickup: "Amroha", drop: "Bareilly" },
    { name: "Aonla to Bareilly Cab", url: "/aonla-to-bareilly-cab", pickup: "Aonla", drop: "Bareilly" },
    { name: "Aonla to Kainchi Dham Cab", url: "/aonla-to-kainchi-dham-cab", pickup: "Aonla", drop: "Kainchi Dham" },
    { name: "Aonla to Manona Dham Cab", url: "/aonla-to-manona-dham-cab", pickup: "Aonla", drop: "Manona Dham" },
    { name: "Ayodhya Taxi Service", url: "/taxi-service-in-ayodhya", pickup: "Ayodhya", drop: "Service Area" },
    { name: "Ayodhya to Agra Cab", url: "/ayodhya-to-agra-cab", pickup: "Ayodhya", drop: "Agra" },
    { name: "Ayodhya to Aligarh Cab", url: "/ayodhya-to-aligarh-cab", pickup: "Ayodhya", drop: "Aligarh" },
    { name: "Ayodhya to Bareilly Cab", url: "/ayodhya-to-bareilly-cab", pickup: "Ayodhya", drop: "Bareilly" },
    { name: "Ayodhya to Dehradun Cab", url: "/ayodhya-to-dehradun-cab", pickup: "Ayodhya", drop: "Dehradun" },
    { name: "Ayodhya to Delhi Cab", url: "/ayodhya-to-delhi-cab", pickup: "Ayodhya", drop: "Delhi" },
    { name: "Ayodhya to Faridabad Cab", url: "/ayodhya-to-faridabad-cab", pickup: "Ayodhya", drop: "Faridabad" },
  { name: "Ayodhya to Ghaziabad Cab", url: "/ayodhya-to-ghaziabad-cab", pickup: "Ayodhya", drop: "Ghaziabad" },
  { name: "Ayodhya to Gurgaon Cab", url: "/ayodhya-to-gurgaon-cab", pickup: "Ayodhya", drop: "Gurgaon" },
  { name: "Ayodhya to Haldwani Cab", url: "/ayodhya-to-haldwani-cab", pickup: "Ayodhya", drop: "Haldwani" },
  { name: "Ayodhya to Haridwar Cab", url: "/ayodhya-to-haridwar-cab", pickup: "Ayodhya", drop: "Haridwar" },
  { name: "Ayodhya to Kainchi dham Cab", url: "/ayodhya-to-kainchi-dham-cab", pickup: "Ayodhya", drop: "Kainchi dham" },
  { name: "Ayodhya to Kanpur Cab", url: "/ayodhya-to-kanpur-cab", pickup: "Ayodhya", drop: "Kanpur" },
  { name: "Ayodhya to Lucknow Cab", url: "/ayodhya-to-lucknow-cab", pickup: "Ayodhya", drop: "Lucknow" },
  { name: "Ayodhya to Manona dham Cab", url: "/ayodhya-to-manona-dham-cab", pickup: "Ayodhya", drop: "Manona dham" },
  { name: "Ayodhya to Mathura Cab", url: "/ayodhya-to-mathura-cab", pickup: "Ayodhya", drop: "Mathura" },
  { name: "Ayodhya to Meerut Cab", url: "/ayodhya-to-meerut-cab", pickup: "Ayodhya", drop: "Meerut" },
  { name: "Ayodhya to Mirzapur Cab", url: "/ayodhya-to-mirzapur-cab", pickup: "Ayodhya", drop: "Mirzapur" },
  { name: "Ayodhya to Moradabad Cab", url: "/ayodhya-to-moradabad-cab", pickup: "Ayodhya", drop: "Moradabad" },
  { name: "Ayodhya to Mussoorie Cab", url: "/ayodhya-to-mussoorie-cab", pickup: "Ayodhya", drop: "Mussoorie" },
  { name: "Ayodhya to Muzaffarnagar Cab", url: "/ayodhya-to-muzaffarnagar-cab", pickup: "Ayodhya", drop: "Muzaffarnagar" },
  { name: "Ayodhya to Nainital Cab", url: "/ayodhya-to-nainital-cab", pickup: "Ayodhya", drop: "Nainital" },
  { name: "Ayodhya to Noida Cab", url: "/ayodhya-to-noida-cab", pickup: "Ayodhya", drop: "Noida" },
  { name: "Ayodhya to Prayagraj Cab", url: "/ayodhya-to-prayagraj-cab", pickup: "Ayodhya", drop: "Prayagraj" },
  { name: "Ayodhya to Rampur Cab", url: "/ayodhya-to-rampur-cab", pickup: "Ayodhya", drop: "Rampur" },
  { name: "Ayodhya to Rishikesh Cab", url: "/ayodhya-to-rishikesh-cab", pickup: "Ayodhya", drop: "Rishikesh" },
  { name: "Ayodhya to Rudrapur Cab", url: "/ayodhya-to-rudrapur-cab", pickup: "Ayodhya", drop: "Rudrapur" },
  { name: "Ayodhya to Shahjahanpur Cab", url: "/ayodhya-to-shahjahanpur-cab", pickup: "Ayodhya", drop: "Shahjahanpur" },
  { name: "Ayodhya to Varanasi Cab", url: "/ayodhya-to-varanasi-cab", pickup: "Ayodhya", drop: "Varanasi" },
  { name: "Ayodhya to Vrindavan Cab", url: "/ayodhya-to-vrindavan-cab", pickup: "Ayodhya", drop: "Vrindavan" },
  { name: "Baheri to Bareilly Cab", url: "/baheri-to-bareilly-cab", pickup: "Baheri", drop: "Bareilly" },
  { name: "Baheri to Delhi Cab", url: "/baheri-to-delhi-cab", pickup: "Baheri", drop: "Delhi" },
  { name: "Baheri to Faridabad Cab", url: "/baheri-to-faridabad-cab", pickup: "Baheri", drop: "Faridabad" },
  { name: "Baheri to Ghaziabad Cab", url: "/baheri-to-ghaziabad-cab", pickup: "Baheri", drop: "Ghaziabad" },
  { name: "Baheri to Gurgaon Cab", url: "/baheri-to-gurgaon-cab", pickup: "Baheri", drop: "Gurgaon" },
  { name: "Baheri to Kainchi dham Cab", url: "/baheri-to-kainchi-dham-cab", pickup: "Baheri", drop: "Kainchi dham" },
  { name: "Baheri to Manona dham Cab", url: "/baheri-to-manona-dham-cab", pickup: "Baheri", drop: "Manona dham" },
  { name: "Baheri to Noida Cab", url: "/baheri-to-noida-cab", pickup: "Baheri", drop: "Noida" },
  { name: "Bahraich to Bareilly Cab", url: "/bahraich-to-bareilly-cab", pickup: "Bahraich", drop: "Bareilly" },
  { name: "Banbasa to Agra Cab", url: "/banbasa-to-agra-cab", pickup: "Banbasa", drop: "Agra" },
  { name: "Banbasa to Ayodhya Cab", url: "/banbasa-to-ayodhya-cab", pickup: "Banbasa", drop: "Ayodhya" },
  { name: "Banbasa to Bareilly Cab", url: "/banbasa-to-bareilly-cab", pickup: "Banbasa", drop: "Bareilly" },
  { name: "Banbasa to Dehradun Cab", url: "/banbasa-to-dehradun-cab", pickup: "Banbasa", drop: "Dehradun" },
  { name: "Banbasa to Delhi Cab", url: "/banbasa-to-delhi-cab", pickup: "Banbasa", drop: "Delhi" },
  { name: "Banbasa to Faridabad Cab", url: "/banbasa-to-faridabad-cab", pickup: "Banbasa", drop: "Faridabad" },
  { name: "Banbasa to Ghaziabad Cab", url: "/banbasa-to-ghaziabad-cab", pickup: "Banbasa", drop: "Ghaziabad" },
  { name: "Banbasa to Gurgaon Cab", url: "/banbasa-to-gurgaon-cab", pickup: "Banbasa", drop: "Gurgaon" },
  { name: "Banbasa to Haldwani Cab", url: "/banbasa-to-haldwani-cab", pickup: "Banbasa", drop: "Haldwani" },
  { name: "Banbasa to Haridwar Cab", url: "/banbasa-to-haridwar-cab", pickup: "Banbasa", drop: "Haridwar" },
  { name: "Banbasa to Kanpur Cab", url: "/banbasa-to-kanpur-cab", pickup: "Banbasa", drop: "Kanpur" },
  { name: "Banbasa to Lucknow Cab", url: "/banbasa-to-lucknow-cab", pickup: "Banbasa", drop: "Lucknow" },
  { name: "Banbasa to Mathura Cab", url: "/banbasa-to-mathura-cab", pickup: "Banbasa", drop: "Mathura" },
  { name: "Banbasa to Meerut Cab", url: "/banbasa-to-meerut-cab", pickup: "Banbasa", drop: "Meerut" },
  { name: "Banbasa to Moradabad Cab", url: "/banbasa-to-moradabad-cab", pickup: "Banbasa", drop: "Moradabad" },
  { name: "Banbasa to Nainital Cab", url: "/banbasa-to-nainital-cab", pickup: "Banbasa", drop: "Nainital" },
  { name: "Banbasa to Noida Cab", url: "/banbasa-to-noida-cab", pickup: "Banbasa", drop: "Noida" },
  { name: "Banbasa to Ramnagar Cab", url: "/banbasa-to-ramnagar-cab", pickup: "Banbasa", drop: "Ramnagar" },
  { name: "Banbasa to Rishikesh Cab", url: "/banbasa-to-rishikesh-cab", pickup: "Banbasa", drop: "Rishikesh" },
  { name: "Banbasa to Vrindavan Cab", url: "/banbasa-to-vrindavan-cab", pickup: "Banbasa", drop: "Vrindavan" },
  { name: "Bareilly to Agra Cab", url: "/bareilly-to-agra-cab", pickup: "Bareilly", drop: "Agra" },
  { name: "Bareilly to Almora Cab", url: "/bareilly-to-almora-cab", pickup: "Bareilly", drop: "Almora" },
  { name: "Bareilly to Amroha Cab", url: "/bareilly-to-amroha-cab", pickup: "Bareilly", drop: "Amroha" },
  { name: "Bareilly to Aonla Cab", url: "/bareilly-to-aonla-cab", pickup: "Bareilly", drop: "Aonla" },
  { name: "Bareilly to Ayodhya Cab", url: "/bareilly-to-ayodhya-cab", pickup: "Bareilly", drop: "Ayodhya" },
  { name: "Bareilly to Baheri Cab", url: "/bareilly-to-baheri-cab", pickup: "Bareilly", drop: "Baheri" },
  { name: "Bareilly to Bahraich Cab", url: "/bareilly-to-bahraich-cab", pickup: "Bareilly", drop: "Bahraich" },
  { name: "Bareilly to Bhimtal Cab", url: "/bareilly-to-bhimtal-cab", pickup: "Bareilly", drop: "Bhimtal" },
  { name: "Bareilly to Bijnor Cab", url: "/bareilly-to-bijnor-cab", pickup: "Bareilly", drop: "Bijnor" },
  { name: "Bareilly to Bisalpur Cab", url: "/bareilly-to-bisalpur-cab", pickup: "Bareilly", drop: "Bisalpur" },
  { name: "Bareilly to Bisauli Cab", url: "/bareilly-to-bisauli-cab", pickup: "Bareilly", drop: "Bisauli" },
  { name: "Bareilly to Budaun Cab", url: "/bareilly-to-budaun-cab", pickup: "Bareilly", drop: "Budaun" },
  { name: "Bareilly to Chandausi Cab", url: "/bareilly-to-chandausi-cab", pickup: "Bareilly", drop: "Chandausi" },
  { name: "Bareilly to Dataganj Cab", url: "/bareilly-to-dataganj-cab", pickup: "Bareilly", drop: "Dataganj" },
  { name: "Bareilly to Dehradun Cab", url: "/bareilly-to-dehradun-cab", pickup: "Bareilly", drop: "Dehradun" },
  { name: "Bareilly to Delhi Airport Cab", url: "/bareilly-to-delhi-airport-cab", pickup: "Bareilly", drop: "Delhi Airport" },
  { name: "Bareilly to Delhi Cab", url: "/bareilly-to-delhi-cab", pickup: "Bareilly", drop: "Delhi" },
  { name: "Bareilly to Dhampur Cab", url: "/bareilly-to-dhampur-cab", pickup: "Bareilly", drop: "Dhampur" },
  { name: "Bareilly to Faridabad Cab", url: "/bareilly-to-faridabad-cab", pickup: "Bareilly", drop: "Faridabad" },
  { name: "Bareilly to Farrukhabad Cab", url: "/bareilly-to-farrukhabad-cab", pickup: "Bareilly", drop: "Farrukhabad" },
  { name: "Bareilly to Ghaziabad Cab", url: "/bareilly-to-ghaziabad-cab", pickup: "Bareilly", drop: "Ghaziabad" },
  { name: "Bareilly to Gola Gokaran Nath Cab", url: "/bareilly-to-gola-gokaran-nath-cab", pickup: "Bareilly", drop: "Gola Gokaran Nath" },
  { name: "Bareilly to Gonda Cab", url: "/bareilly-to-gonda-cab", pickup: "Bareilly", drop: "Gonda" },
  { name: "Bareilly to Gurgaon Cab", url: "/bareilly-to-gurgaon-cab", pickup: "Bareilly", drop: "Gurgaon" },
  { name: "Bareilly to Haldwani Cab", url: "/bareilly-to-haldwani-cab", pickup: "Bareilly", drop: "Haldwani" },
  { name: "Bareilly to Hardoi Cab", url: "/bareilly-to-hardoi-cab", pickup: "Bareilly", drop: "Hardoi" },
  { name: "Bareilly to Haridwar Cab", url: "/bareilly-to-haridwar-cab", pickup: "Bareilly", drop: "Haridwar" },
  { name: "Bareilly to Jalalabad Cab", url: "/bareilly-to-jalalabad-cab", pickup: "Bareilly", drop: "Jalalabad" },
  { name: "Bareilly to Kanpur Cab", url: "/bareilly-to-kanpur-cab", pickup: "Bareilly", drop: "Kanpur" },
  { name: "Bareilly to Kasganj Cab", url: "/bareilly-to-kasganj-cab", pickup: "Bareilly", drop: "Kasganj" },
  { name: "Bareilly to Kashipur Cab", url: "/bareilly-to-kashipur-cab", pickup: "Bareilly", drop: "Kashipur" },
  { name: "Bareilly to Katra Cab", url: "/bareilly-to-katra-cab", pickup: "Bareilly", drop: "Katra" },
  { name: "Bareilly to Khatima Cab", url: "/bareilly-to-khatima-cab", pickup: "Bareilly", drop: "Khatima" },
  { name: "Bareilly to Kotdwar Cab", url: "/bareilly-to-kotdwar-cab", pickup: "Bareilly", drop: "Kotdwar" },
  { name: "Bareilly to Lakhimpur Cab", url: "/bareilly-to-lakhimpur-cab", pickup: "Bareilly", drop: "Lakhimpur" },
  { name: "Bareilly to Lohaghat Cab", url: "/bareilly-to-lohaghat-cab", pickup: "Bareilly", drop: "Lohaghat" },
  { name: "Bareilly to Lucknow Cab", url: "/bareilly-to-lucknow-cab", pickup: "Bareilly", drop: "Lucknow" },
  { name: "Bareilly to Mathura Cab", url: "/bareilly-to-mathura-cab", pickup: "Bareilly", drop: "Mathura" },
  { name: "Bareilly to Meerut Cab", url: "/bareilly-to-meerut-cab", pickup: "Bareilly", drop: "Meerut" },
  { name: "Bareilly to Moradabad Cab", url: "/bareilly-to-moradabad-cab", pickup: "Bareilly", drop: "Moradabad" },
  { name: "Bareilly to Muzaffarnagar Cab", url: "/bareilly-to-muzaffarnagar-cab", pickup: "Bareilly", drop: "Muzaffarnagar" },
  { name: "Bareilly to Nainital Cab", url: "/bareilly-to-nainital-cab", pickup: "Bareilly", drop: "Nainital" },
  { name: "Bareilly to Noida Cab", url: "/bareilly-to-noida-cab", pickup: "Bareilly", drop: "Noida" },
  { name: "Bareilly to Palia Kalan Cab", url: "/bareilly-to-palia-kalan-cab", pickup: "Bareilly", drop: "Palia Kalan" },
  { name: "Bareilly to Pilibhit Cab", url: "/bareilly-to-pilibhit-cab", pickup: "Bareilly", drop: "Pilibhit" },
  { name: "Bareilly to Pithoragarh Cab", url: "/bareilly-to-pithoragarh-cab", pickup: "Bareilly", drop: "Pithoragarh" },
  { name: "Bareilly to Puranpur Cab", url: "/bareilly-to-puranpur-cab", pickup: "Bareilly", drop: "Puranpur" },
  { name: "Bareilly to Rampur Cab", url: "/bareilly-to-rampur-cab", pickup: "Bareilly", drop: "Rampur" },
  { name: "Bareilly to Ranikhet Cab", url: "/bareilly-to-ranikhet-cab", pickup: "Bareilly", drop: "Ranikhet" },
  { name: "Bareilly to Roorkee Cab", url: "/bareilly-to-roorkee-cab", pickup: "Bareilly", drop: "Roorkee" },
  { name: "Bareilly to Rudrapur Cab", url: "/bareilly-to-rudrapur-cab", pickup: "Bareilly", drop: "Rudrapur" },
  { name: "Bareilly to Shahjahanpur Cab", url: "/bareilly-to-shahjahanpur-cab", pickup: "Bareilly", drop: "Shahjahanpur" },
  { name: "Bareilly to Sitapur Cab", url: "/bareilly-to-sitapur-cab", pickup: "Bareilly", drop: "Sitapur" },
  { name: "Bareilly to Sitarganj Cab", url: "/bareilly-to-sitarganj-cab", pickup: "Bareilly", drop: "Sitarganj" },
  { name: "Bareilly to Tanakpur Cab", url: "/bareilly-to-tanakpur-cab", pickup: "Bareilly", drop: "Tanakpur" },
  { name: "Bareilly to Ujhani Cab", url: "/bareilly-to-ujhani-cab", pickup: "Bareilly", drop: "Ujhani" },
  { name: "Bazpur Taxi Service", url: "/taxi-service-in-bazpur", pickup: "Bazpur", drop: "" },
  { name: "Bhimtal to Agra Cab", url: "/bhimtal-to-agra-cab", pickup: "Bhimtal", drop: "Agra" },
  { name: "Bhimtal to Ayodhya Cab", url: "/bhimtal-to-ayodhya-cab", pickup: "Bhimtal", drop: "Ayodhya" },
  { name: "Bhimtal to Bareilly Cab", url: "/bhimtal-to-bareilly-cab", pickup: "Bhimtal", drop: "Bareilly" },
  { name: "Bhimtal to Dehradun Cab", url: "/bhimtal-to-dehradun-cab", pickup: "Bhimtal", drop: "Dehradun" },
  { name: "Bhimtal to Delhi Cab", url: "/bhimtal-to-delhi-cab", pickup: "Bhimtal", drop: "Delhi" },
  { name: "Bhimtal to Faridabad Cab", url: "/bhimtal-to-faridabad-cab", pickup: "Bhimtal", drop: "Faridabad" },
  { name: "Bhimtal to Ghaziabad Cab", url: "/bhimtal-to-ghaziabad-cab", pickup: "Bhimtal", drop: "Ghaziabad" },
  { name: "Bhimtal to Gurgaon Cab", url: "/bhimtal-to-gurgaon-cab", pickup: "Bhimtal", drop: "Gurgaon" },
  { name: "Bhimtal to Haridwar Cab", url: "/bhimtal-to-haridwar-cab", pickup: "Bhimtal", drop: "Haridwar" },
  { name: "Bhimtal to Kanpur Cab", url: "/bhimtal-to-kanpur-cab", pickup: "Bhimtal", drop: "Kanpur" },
  { name: "Bhimtal to Lucknow Cab", url: "/bhimtal-to-lucknow-cab", pickup: "Bhimtal", drop: "Lucknow" },
  { name: "Bhimtal to Mathura Cab", url: "/bhimtal-to-mathura-cab", pickup: "Bhimtal", drop: "Mathura" },
  { name: "Bhimtal to Meerut Cab", url: "/bhimtal-to-meerut-cab", pickup: "Bhimtal", drop: "Meerut" },
  { name: "Bhimtal to Moradabad Cab", url: "/bhimtal-to-moradabad-cab", pickup: "Bhimtal", drop: "Moradabad" },
  { name: "Bhimtal to Noida Cab", url: "/bhimtal-to-noida-cab", pickup: "Bhimtal", drop: "Noida" },
  { name: "Bhimtal to Prayagraj Cab", url: "/bhimtal-to-prayagraj-cab", pickup: "Bhimtal", drop: "Prayagraj" },
  { name: "Bhimtal to Rishikesh Cab", url: "/bhimtal-to-rishikesh-cab", pickup: "Bhimtal", drop: "Rishikesh" },
  { name: "Bhimtal to Roorkee Cab", url: "/bhimtal-to-roorkee-cab", pickup: "Bhimtal", drop: "Roorkee" },
  { name: "Bhimtal to Saharanpur Cab", url: "/bhimtal-to-saharanpur-cab", pickup: "Bhimtal", drop: "Saharanpur" },
  { name: "Bhimtal to Varanasi Cab", url: "/bhimtal-to-varanasi-cab", pickup: "Bhimtal", drop: "Varanasi" },
  { name: "Bijnor Taxi Service", url: "/taxi-service-in-bijnor", pickup: "Bijnor", drop: "" },
  { name: "Bijnor to Bareilly Cab", url: "/bijnor-to-bareilly-cab", pickup: "Bijnor", drop: "Bareilly" },
  { name: "Bisalpur to Bareilly Cab", url: "/bisalpur-to-bareilly-cab", pickup: "Bisalpur", drop: "Bareilly" },
  { name: "Bisauli to Bareilly Cab", url: "/bisauli-to-bareilly-cab", pickup: "Bisauli", drop: "Bareilly" },
  { name: "Budaun Taxi Service", url: "/taxi-service-budaun-one-way-cab-outstation-car-hire-airport-taxi", pickup: "Budaun", drop: "" },
  { name: "Budaun to Agra Cab", url: "/budaun-to-agra-cab", pickup: "Budaun", drop: "Agra" },
  { name: "Budaun to Ayodhya Cab", url: "/budaun-to-ayodhya-cab", pickup: "Budaun", drop: "Ayodhya" },
  { name: "Budaun to Bareilly Cab", url: "/budaun-to-bareilly-cab", pickup: "Budaun", drop: "Bareilly" },
  { name: "Budaun to Chandigarh Cab", url: "/budaun-to-chandigarh-cab", pickup: "Budaun", drop: "Chandigarh" },
  { name: "Budaun to Dehradun Cab", url: "/budaun-to-dehradun-cab", pickup: "Budaun", drop: "Dehradun" },
  { name: "Budaun to Delhi Cab", url: "/budaun-to-delhi-cab", pickup: "Budaun", drop: "Delhi" },
  { name: "Budaun to Haldwani Cab", url: "/budaun-to-haldwani-cab", pickup: "Budaun", drop: "Haldwani" },
  { name: "Budaun to Haridwar Cab", url: "/budaun-to-haridwar-cab", pickup: "Budaun", drop: "Haridwar" },
  { name: "Budaun to Jaipur Cab", url: "/budaun-to-jaipur-cab", pickup: "Budaun", drop: "Jaipur" },
  { name: "Budaun to Kanpur Cab", url: "/budaun-to-kanpur-cab", pickup: "Budaun", drop: "Kanpur" },
  { name: "Budaun to Lucknow Cab", url: "/budaun-to-lucknow-cab", pickup: "Budaun", drop: "Lucknow" },
  { name: "Budaun to Mathura Cab", url: "/budaun-to-mathura-cab", pickup: "Budaun", drop: "Mathura" },
  { name: "Budaun to Nainital Cab", url: "/budaun-to-nainital-cab", pickup: "Budaun", drop: "Nainital" },
  { name: "Budaun to Noida Cab", url: "/budaun-to-noida-cab", pickup: "Budaun", drop: "Noida" },
  { name: "Budaun to Shimla Cab", url: "/budaun-to-shimla-cab", pickup: "Budaun", drop: "Shimla" },
  { name: "Chandausi Taxi Service", url: "/taxi-service-in-chandausi", pickup: "Chandausi", drop: "" },
  { name: "Chandausi to Bareilly Cab", url: "/chandausi-to-bareilly-cab", pickup: "Chandausi", drop: "Bareilly" },
  { name: "Dataganj to Bareilly Cab", url: "/dataganj-to-bareilly-cab", pickup: "Dataganj", drop: "Bareilly" },
  { name: "Dehradun Taxi Service", url: "/taxi-service-in-dehradun", pickup: "Dehradun", drop: "" },
  { name: "Dehradun to Agra Cab", url: "/dehradun-to-agra-cab", pickup: "Dehradun", drop: "Agra" },
  { name: "Dhampur Taxi Service", url: "/taxi-service-in-dhampur", pickup: "Dhampur", drop: "Dhampur" },
  { name: "Dhampur to Bareilly Cab", url: "/dhampur-to-bareilly-cab", pickup: "Dhampur", drop: "Bareilly" },
  { name: "Faridabad Taxi Service", url: "/taxi-service-in-faridabad", pickup: "Faridabad", drop: "Faridabad" },
  { name: "Faridabad to Agra Cab", url: "/faridabad-to-agra-cab", pickup: "Faridabad", drop: "Agra" },
  { name: "Faridabad to Aligarh Cab", url: "/faridabad-to-aligarh-cab", pickup: "Faridabad", drop: "Aligarh" },
  { name: "Faridabad to Almora Cab", url: "/faridabad-to-almora-cab", pickup: "Faridabad", drop: "Almora" },
  { name: "Faridabad to Ayodhya Cab", url: "/faridabad-to-ayodhya-cab", pickup: "Faridabad", drop: "Ayodhya" },
  { name: "Faridabad To Bareilly Cab", url: "/book-faridabad-to-bareilly-cabs-cheapest-one-way-taxi-fare", pickup: "Faridabad", drop: "Bareilly" },
  { name: "Faridabad to Bhimtal Cab", url: "/faridabad-to-bhimtal-cab", pickup: "Faridabad", drop: "Bhimtal" },
  { name: "Faridabad to Bhowali Cab", url: "/faridabad-to-bhowali-cab-booking", pickup: "Faridabad", drop: "Bhowali" },
  { name: "Faridabad to Bijnor Cab", url: "/faridabad-to-bijnor-cab", pickup: "Faridabad", drop: "Bijnor" },
  { name: "Faridabad to Chandigarh Cab", url: "/faridabad-to-chandigarh-cab", pickup: "Faridabad", drop: "Chandigarh" },
  { name: "Faridabad to Dehradun Cab", url: "/faridabad-to-dehradun-cab", pickup: "Faridabad", drop: "Dehradun" },
  { name: "Faridabad to Dhampur Cab", url: "/faridabad-to-dhampur-cab", pickup: "Faridabad", drop: "Dhampur" },
  { name: "Faridabad to Etah Cab", url: "/faridabad-to-etah-cab", pickup: "Faridabad", drop: "Etah" },
  { name: "Faridabad to Etawah Cab", url: "/faridabad-to-etawah-cab", pickup: "Faridabad", drop: "Etawah" },
  { name: "Faridabad to Farrukhabad Cab", url: "/faridabad-to-farrukhabad-cab", pickup: "Faridabad", drop: "Farrukhabad" },
  { name: "Faridabad to Haldwani Cab", url: "/faridabad-to-haldwani-cab", pickup: "Faridabad", drop: "Haldwani" },
  { name: "Faridabad to Haridwar Cab", url: "/faridabad-to-haridwar-cab", pickup: "Faridabad", drop: "Haridwar" },
  { name: "Faridabad to Jaipur Cab", url: "/faridabad-to-jaipur-cab", pickup: "Faridabad", drop: "Jaipur" },
  { name: "Faridabad to Kainchi dham Cab", url: "/faridabad-to-kainchi-dham-cab", pickup: "Faridabad", drop: "Kainchi dham" },
  { name: "Faridabad to Kanpur Cab", url: "/faridabad-to-kanpur-cab", pickup: "Faridabad", drop: "Kanpur" },
  { name: "Faridabad to Kashipur Cab", url: "/faridabad-to-kashipur-cab", pickup: "Faridabad", drop: "Kashipur" },
  { name: "Faridabad to Khatima Cab", url: "/faridabad-to-khatima-cab", pickup: "Faridabad", drop: "Khatima" },
  { name: "Faridabad to Lakhimpur Cab", url: "/faridabad-to-lakhimpur-cab", pickup: "Faridabad", drop: "Lakhimpur" },
  { name: "Faridabad to Lucknow Cab", url: "/faridabad-to-lucknow-cab", pickup: "Faridabad", drop: "Lucknow" },
  { name: "Faridabad to Manona dham Cab", url: "/faridabad-to-manona-dham-cab", pickup: "Faridabad", drop: "Manona dham" },
  { name: "Faridabad to Mathura Cab", url: "/faridabad-to-mathura-cab", pickup: "Faridabad", drop: "Mathura" },
  { name: "Faridabad to Meerut Cab", url: "/faridabad-to-meerut-cab", pickup: "Faridabad", drop: "Meerut" },
  { name: "Faridabad to Mussoorie Cab", url: "/faridabad-to-mussoorie-cab", pickup: "Faridabad", drop: "Mussoorie" },
  { name: "Faridabad to Pilibhit Cab", url: "/faridabad-to-pilibhit-cab", pickup: "Faridabad", drop: "Pilibhit" },
  { name: "Faridabad to Prayagraj Cab", url: "/faridabad-to-prayagraj-cab", pickup: "Faridabad", drop: "Prayagraj" },
  { name: "Faridabad to Ramanagar jim corbett Cab", url: "/faridabad-to-ramanagar-jim-corbett-cab", pickup: "Faridabad", drop: "Ramanagar jim corbett" },
  { name: "Faridabad to Ranikhet Cab", url: "/faridabad-to-ranikhet-cab", pickup: "Faridabad", drop: "Ranikhet" },
  { name: "Faridabad to Rishikesh Cab", url: "/faridabad-to-rishikesh-cab", pickup: "Faridabad", drop: "Rishikesh" },
  { name: "Faridabad to Roorkee Cab", url: "/faridabad-to-roorkee-cab", pickup: "Faridabad", drop: "Roorkee" },
  { name: "Faridabad to Rudrapur Cab", url: "/faridabad-to-rudrapur-cab", pickup: "Faridabad", drop: "Rudrapur" },
  { name: "Faridabad to Saharanpur Cab", url: "/faridabad-to-saharanpur-cab", pickup: "Faridabad", drop: "Saharanpur" },
  { name: "Faridabad to Shahjahanpur Cab", url: "/faridabad-to-shahjahanpur-cab", pickup: "Faridabad", drop: "Shahjahanpur" },
  { name: "Faridabad to Sitapur Cab", url: "/faridabad-to-sitapur-cab", pickup: "Faridabad", drop: "Sitapur" },
  { name: "Faridabad to Sitarganj Cab", url: "/faridabad-to-sitarganj-cab", pickup: "Faridabad", drop: "Sitarganj" },
  { name: "Faridabad to Tanakpur Cab", url: "/faridabad-to-tanakpur-cab", pickup: "Faridabad", drop: "Tanakpur" },
  { name: "Faridabad to Varanasi Cab", url: "/faridabad-to-varanasi-cab", pickup: "Faridabad", drop: "Varanasi" },
  { name: "Faridabad to Vridavan Cab", url: "/faridabad-to-vridavan-cab", pickup: "Faridabad", drop: "Vridavan" },
  { name: "Farukhabad to Bareilly Cab", url: "/farukhabad-to-bareilly-cab", pickup: "Farukhabad", drop: "Bareilly" },
  { name: "Ghaziabad Taxi Service", url: "/best-outstation-cab-in-ghaziabad-for-one-way-round-trip-taxi-service", pickup: "Ghaziabad", drop: "Ghaziabad" },
  { name: "Ghaziabad to Agra Cab", url: "/ghaziabad-to-agra-cab", pickup: "Ghaziabad", drop: "Agra" },
  { name: "Ghaziabad to Aligarh Cab", url: "/ghaziabad-to-aligarh-cab", pickup: "Ghaziabad", drop: "Aligarh" },
  { name: "Ghaziabad to Almora Cab", url: "/ghaziabad-to-almora-cab", pickup: "Ghaziabad", drop: "Almora" },
  { name: "Ghaziabad to Ayodhya Cab", url: "/ghaziabad-to-ayodhya-cab", pickup: "Ghaziabad", drop: "Ayodhya" },
  { name: "Ghaziabad to Bareilly Cab", url: "/ghaziabad-to-bareilly-cab", pickup: "Ghaziabad", drop: "Bareilly" },
  { name: "Ghaziabad to Bhopal Cab", url: "/ghaziabad-to-bhopal-cab", pickup: "Ghaziabad", drop: "Bhopal" },
  { name: "Ghaziabad to Chandigarh Cab", url: "/ghaziabad-to-chandigarh-cab", pickup: "Ghaziabad", drop: "Chandigarh" },
  { name: "Ghaziabad to Dehradun Cab", url: "/ghaziabad-to-dehradun-cab", pickup: "Ghaziabad", drop: "Dehradun" },
  { name: "Ghaziabad to Dhampur Cab", url: "/ghaziabad-to-dhampur-cab", pickup: "Ghaziabad", drop: "Dhampur" },
  { name: "Ghaziabad to Etawah Cab", url: "/ghaziabad-to-etawah-cab", pickup: "Ghaziabad", drop: "Etawah" },
  { name: "Ghaziabad to Faridabad Cab", url: "/ghaziabad-to-faridabad-cab", pickup: "Ghaziabad", drop: "Faridabad" },
  { name: "Ghaziabad to Haldwani Cab", url: "/ghaziabad-to-haldwani-cab", pickup: "Ghaziabad", drop: "Haldwani" },
  { name: "Ghaziabad to Haridwar Cab", url: "/ghaziabad-to-haridwar-cab", pickup: "Ghaziabad", drop: "Haridwar" },
  { name: "Ghaziabad to Jaipur Cab", url: "/ghaziabad-to-jaipur-cab", pickup: "Ghaziabad", drop: "Jaipur" },
  { name: "Ghaziabad to Kainchi dham Cab", url: "/ghaziabad-to-kainchi-dham-cab", pickup: "Ghaziabad", drop: "Kainchi dham" },
  { name: "Ghaziabad to Kanpur Cab", url: "/ghaziabad-to-kanpur-cab", pickup: "Ghaziabad", drop: "Kanpur" },
  { name: "Ghaziabad to Kashipur Cab", url: "/ghaziabad-to-kashipur-cab", pickup: "Ghaziabad", drop: "Kashipur" },
  { name: "Gorakhpur to Noida Cab", url: "/gorakhpur-to-noida-cab", pickup: "Gorakhpur", drop: "Noida" },
  { name: "Gorakhpur to Ramnagar Cab", url: "/gorakhpur-to-ramnagar-cab", pickup: "Gorakhpur", drop: "Ramnagar" },
  { name: "Gorakhpur to Rishikesh Cab", url: "/gorakhpur-to-rishikesh-cab", pickup: "Gorakhpur", drop: "Rishikesh" },
  { name: "Gorakhpur to Rudrapur Cab", url: "/gorakhpur-to-rudrapur-cab", pickup: "Gorakhpur", drop: "Rudrapur" },
  { name: "Gorakhpur to Shahjahanpur Cab", url: "/gorakhpur-to-shahjahanpur-cab", pickup: "Gorakhpur", drop: "Shahjahanpur" },
  { name: "Gorakhpur to Vrindavan Cab", url: "/gorakhpur-to-vrindavan-cab", pickup: "Gorakhpur", drop: "Vrindavan" },
  { name: "Gurgaon Taxi Service", url: "/best-outstation-cab-in-gurugram-for-one-way-round-trip-taxi-service", pickup: "Gurgaon", drop: "Various" },
  { name: "Gurgaon to Agra Cab", url: "/gurgaon-to-agra-cab", pickup: "Gurgaon", drop: "Agra" },
  { name: "Gurgaon to Aligarh Cab", url: "/gurgaon-to-aligarh-cab", pickup: "Gurgaon", drop: "Aligarh" },
  { name: "Gurgaon to Almora Cab", url: "/gurgaon-to-almora-cab", pickup: "Gurgaon", drop: "Almora" },
  { name: "Gurgaon to Ayodhya Cab", url: "/gurgaon-to-ayodhya-cab", pickup: "Gurgaon", drop: "Ayodhya" },
  { name: "Gurgaon To Bareilly Cab", url: "/book-gurgaon-to-bareilly-cabs-cheapest-one-way-taxi-fare", pickup: "Gurgaon", drop: "Bareilly" },
  { name: "Gurgaon to Bhimtal Cab", url: "/gurgaon-to-bhimtal-cab", pickup: "Gurgaon", drop: "Bhimtal" },
  { name: "Gurgaon to Bhowali Cab", url: "/gurgaon-to-bhowali-cab", pickup: "Gurgaon", drop: "Bhowali" },
  { name: "Gurgaon to Bijnor Cab", url: "/gurgaon-to-bijnor-cab", pickup: "Gurgaon", drop: "Bijnor" },
  { name: "Gurgaon to Chandigarh Cab", url: "/gurgaon-to-chandigarh-cab", pickup: "Gurgaon", drop: "Chandigarh" },
  { name: "Gurgaon to Dehradun Cab", url: "/gurgaon-to-dehradun-cab", pickup: "Gurgaon", drop: "Dehradun" },
  { name: "Gurgaon to Dhampur Cab", url: "/gurgaon-to-dhampur-cab", pickup: "Gurgaon", drop: "Dhampur" },
  { name: "Gurgaon to Etah Cab", url: "/gurgaon-to-etah-cab", pickup: "Gurgaon", drop: "Etah" },
  { name: "Gurgaon to Etawah Cab", url: "/gurgaon-to-etawah-cab", pickup: "Gurgaon", drop: "Etawah" },
  { name: "Gurgaon to Farrukhabad Cab", url: "/gurgaon-to-farrukhabad-cab", pickup: "Gurgaon", drop: "Farrukhabad" },
  { name: "Gurgaon to Haldwani Cab", url: "/gurgaon-to-haldwani-cab", pickup: "Gurgaon", drop: "Haldwani" },
  { name: "Gurgaon to Haridwar Cab", url: "/gurgaon-to-haridwar-cab", pickup: "Gurgaon", drop: "Haridwar" },
  { name: "Gurgaon to Jaipur Cab", url: "/gurgaon-to-jaipur-cab", pickup: "Gurgaon", drop: "Jaipur" },
  { name: "Gurgaon to Kainchi Dham Cab", url: "/gurgaon-to-kainchi-dham-cab", pickup: "Gurgaon", drop: "Kainchi Dham" },
  { name: "Gurgaon to Kanpur Cab", url: "/gurgaon-to-kanpur-cab", pickup: "Gurgaon", drop: "Kanpur" },
  { name: "Gurgaon to Kashipur Cab", url: "/gurgaon-to-kashipur-cab", pickup: "Gurgaon", drop: "Kashipur" },
  { name: "Gurgaon to Lakhimpur Cab", url: "/gurgaon-to-lakhimpur-cab", pickup: "Gurgaon", drop: "Lakhimpur" },
  { name: "Gurgaon to Lucknow Cab", url: "/gurgaon-to-lucknow-cab", pickup: "Gurgaon", drop: "Lucknow" },
  { name: "Gurgaon to Manona Dham Cab", url: "/gurgaon-to-manona-dham-cab", pickup: "Gurgaon", drop: "Manona Dham" },
  { name: "Gurgaon to Mathura Cab", url: "/gurgaon-to-mathura-cab", pickup: "Gurgaon", drop: "Mathura" },
  { name: "Gurgaon to Meerut Cab", url: "/gurgaon-to-meerut-cab", pickup: "Gurgaon", drop: "Meerut" },
  { name: "Gurgaon to Moradabad Cab", url: "/gurgaon-to-moradabad-cab", pickup: "Gurgaon", drop: "Moradabad" },
  { name: "Gurgaon to Mussoorie Cab", url: "/gurgaon-to-mussoorie-cab", pickup: "Gurgaon", drop: "Mussoorie" },
  { name: "Gurgaon to Pilibhit Cab", url: "/gurgaon-to-pilibhit-cab", pickup: "Gurgaon", drop: "Pilibhit" },
  { name: "Gurgaon to Prayagraj Cab", url: "/gurgaon-to-prayagraj-cab", pickup: "Gurgaon", drop: "Prayagraj" },
  { name: "Gurgaon to Ramnagar Jim Corbett Cab", url: "/gurgaon-to-ramnagar-jim-corbett-cab", pickup: "Gurgaon", drop: "Ramnagar (Jim Corbett)" },
  { name: "Gurgaon to Rampur Cab", url: "/gurgaon-to-rampur-cab", pickup: "Gurgaon", drop: "Rampur" },
  { name: "Gurgaon to Ranikhet Cab", url: "/gurgaon-to-ranikhet-cab", pickup: "Gurgaon", drop: "Ranikhet" },
  { name: "Gurgaon to Rishikesh Cab", url: "/gurgaon-to-rishikesh-cab", pickup: "Gurgaon", drop: "Rishikesh" },
  { name: "Gurgaon to Roorkee Cab", url: "/gurgaon-to-roorkee-cab", pickup: "Gurgaon", drop: "Roorkee" },
  { name: "Gurgaon to Rudrapur Cab", url: "/gurgaon-to-rudrapur-cab", pickup: "Gurgaon", drop: "Rudrapur" },
  { name: "Gurgaon to Saharanpur Cab", url: "/gurgaon-to-saharanpur-cab", pickup: "Gurgaon", drop: "Saharanpur" },
  { name: "Gurgaon to Shahjahanpur Cab", url: "/gurgaon-to-shahjahanpur-cab", pickup: "Gurgaon", drop: "Shahjahanpur" },
  { name: "Gurgaon to Sitapur Cab", url: "/gurgaon-to-sitapur-cab", pickup: "Gurgaon", drop: "Sitapur" },
  { name: "Gurgaon to Sitarganj Cab", url: "/gurgaon-to-sitarganj-cab", pickup: "Gurgaon", drop: "Sitarganj" },
  { name: "Gurgaon to Tanakpur Cab", url: "/gurgaon-to-tanakpur-cab", pickup: "Gurgaon", drop: "Tanakpur" },
  { name: "Gurgaon to Varanasi Cab", url: "/gurgaon-to-varanasi-cab", pickup: "Gurgaon", drop: "Varanasi" },
  { name: "Gurgaon to Vrindavan Cab", url: "/gurgaon-to-vrindavan-cab", pickup: "Gurgaon", drop: "Vrindavan" },
  { name: "Haldwani Taxi Service", url: "https://gulaticab.com/haldwani-one-way-taxi/", pickup: "Haldwani", drop: "Haldwani" },
  { name: "Haldwani to Agra Cab", url: "https://gulaticab.com/haldwani-to-agra-cab/", pickup: "Haldwani", drop: "Agra" },
  { name: "Haldwani to Ayodhya Cab", url: "https://gulaticab.com/haldwani-to-ayodhya-cab/", pickup: "Haldwani", drop: "Ayodhya" },
  { name: "Haldwani To Bareilly Taxi", url: "https://gulaticab.com/book-haldwani-to-bareilly-cabs-cheapest-one-way-taxi-fare/", pickup: "Haldwani", drop: "Bareilly" },
  { name: "Haldwani to Dehradun Cab", url: "https://gulaticab.com/haldwani-to-dehradun-cab/", pickup: "Haldwani", drop: "Dehradun" },
  { name: "Haldwani to Delhi Cab", url: "https://gulaticab.com/haldwani-to-delhi-cab/", pickup: "Haldwani", drop: "Delhi" },
  { name: "Haldwani to Faridabad Cab", url: "https://gulaticab.com/haldwani-to-faridabad-cab/", pickup: "Haldwani", drop: "Faridabad" },
  { name: "Haldwani to Ghaziabad Cab", url: "https://gulaticab.com/haldwani-to-ghaziabad-cab/", pickup: "Haldwani", drop: "Ghaziabad" },
  { name: "Haldwani to Gurgaon Cab", url: "https://gulaticab.com/haldwani-to-gurgaon-cab/", pickup: "Haldwani", drop: "Gurgaon" },
  { name: "Haldwani to Haridwar Cab", url: "https://gulaticab.com/haldwani-to-haridwar-cab/", pickup: "Haldwani", drop: "Haridwar" },
  { name: "Haldwani to Kanpur Cab", url: "https://gulaticab.com/haldwani-to-kanpur-cab/", pickup: "Haldwani", drop: "Kanpur" },
  { name: "Haldwani to Lucknow Cab", url: "https://gulaticab.com/haldwani-to-lucknow-cab/", pickup: "Haldwani", drop: "Lucknow" },
  { name: "Haldwani to Mathura Cab", url: "https://gulaticab.com/haldwani-to-mathura-cab/", pickup: "Haldwani", drop: "Mathura" },
  { name: "Haldwani to Meerut Cab", url: "https://gulaticab.com/haldwani-to-meerut-cab/", pickup: "Haldwani", drop: "Meerut" },
  { name: "Haldwani to Moradabad Cab", url: "https://gulaticab.com/haldwani-to-moradabad-cab/", pickup: "Haldwani", drop: "Moradabad" },
  { name: "Haldwani to Mussoorie Cab", url: "https://gulaticab.com/haldwani-to-mussoorie-cab/", pickup: "Haldwani", drop: "Mussoorie" },
  { name: "Haldwani to Noida Cab", url: "https://gulaticab.com/haldwani-to-noida-cab/", pickup: "Haldwani", drop: "Noida" },
  { name: "Haldwani to Ramnagar taxi", url: "https://gulaticab.com/haldwani-to-ramnagar-taxi/", pickup: "Haldwani", drop: "Ramnagar" },
  { name: "Haldwani to Rampur Cab", url: "https://gulaticab.com/haldwani-to-rampur-cab/", pickup: "Haldwani", drop: "Rampur" },
  { name: "Haldwani to Rishikesh Cab", url: "https://gulaticab.com/haldwani-to-rishikesh-cab/", pickup: "Haldwani", drop: "Rishikesh" },
  { name: "Haldwani to Roorkee Cab", url: "https://gulaticab.com/haldwani-to-roorkee-cab/", pickup: "Haldwani", drop: "Roorkee" },
  { name: "Haldwani to Saharanpur Cab", url: "https://gulaticab.com/haldwani-to-saharanpur-cab/", pickup: "Haldwani", drop: "Saharanpur" },
  { name: "Hardoi to Bareilly Cab", url: "https://gulaticab.com/hardoi-to-bareilly-cab/", pickup: "Hardoi", drop: "Bareilly" },
  { name: "Haridwar Taxi Service", url: "https://gulaticab.com/taxi-service-in-haridwar/", pickup: "Haridwar", drop: "Haridwar" },
  { name: "Haridwar to Agra Cab", url: "https://gulaticab.com/haridwar-to-agra-cab/", pickup: "Haridwar", drop: "Agra" },
  { name: "Haridwar to Aligarh Cab", url: "https://gulaticab.com/haridwar-to-aligarh-cab/", pickup: "Haridwar", drop: "Aligarh" },
  { name: "Haridwar to Ayodhya Cab", url: "https://gulaticab.com/haridwar-to-ayodhya-cab/", pickup: "Haridwar", drop: "Ayodhya" },
  { name: "Haridwar to Bareilly Cab", url: "https://gulaticab.com/book-haridwar-to-bareilly-cabs-cheapest-one-way-taxi-fare/", pickup: "Haridwar", drop: "Bareilly" },
  { name: "Haridwar to Dehradun Cab", url: "https://gulaticab.com/haridwar-to-dehradun-cab/", pickup: "Haridwar", drop: "Dehradun" },
  { name: "Haridwar to Delhi Cab", url: "https://gulaticab.com/haridwar-to-delhi-cab/", pickup: "Haridwar", drop: "Delhi" },
  { name: "Haridwar to Faridabad Cab", url: "https://gulaticab.com/haridwar-to-faridabad-cab/", pickup: "Haridwar", drop: "Faridabad" },
  { name: "Haridwar to Ghaziabad Cab", url: "https://gulaticab.com/haridwar-to-ghaziabad-cab/", pickup: "Haridwar", drop: "Ghaziabad" },
  { name: "Haridwar to Gurgaon Cab", url: "https://gulaticab.com/haridwar-to-gurgaon-cab/", pickup: "Haridwar", drop: "Gurgaon" },
  { name: "Haridwar to Haldwani Cab", url: "https://gulaticab.com/haridwar-to-haldwani-cab/", pickup: "Haridwar", drop: "Haldwani" },
  { name: "Haridwar to Kainchi dham Cab", url: "https://gulaticab.com/haridwar-to-kainchi-dham-cab/", pickup: "Haridwar", drop: "Kainchi dham" },
  { name: "Haridwar to Lucknow Cab", url: "https://gulaticab.com/haridwar-to-lucknow-cab/", pickup: "Haridwar", drop: "Lucknow" },
  { name: "Haridwar to Manona dham Cab", url: "https://gulaticab.com/haridwar-to-manona-dham-cab/", pickup: "Haridwar", drop: "Manona dham" },
  { name: "Haridwar to Mathura Cab", url: "https://gulaticab.com/haridwar-to-mathura-cab/", pickup: "Haridwar", drop: "Mathura" },
  { name: "Haridwar to Mussoorie Cab", url: "https://gulaticab.com/haridwar-to-mussoorie-cab/", pickup: "Haridwar", drop: "Mussoorie" },
  { name: "Haridwar to Nainital Cab", url: "https://gulaticab.com/haridwar-to-nainital-cab/", pickup: "Haridwar", drop: "Nainital" },
  { name: "Haridwar to Noida Cab", url: "https://gulaticab.com/haridwar-to-noida-cab/", pickup: "Haridwar", drop: "Noida" },
  { name: "Haridwar to Rishikesh Cab", url: "https://gulaticab.com/haridwar-to-rishikesh-cab/", pickup: "Haridwar", drop: "Rishikesh" },
  { name: "Haridwar to Vrindavan Cab", url: "https://gulaticab.com/haridwar-to-vrindavan-cab/", pickup: "Haridwar", drop: "Vrindavan" },
  { name: "Jaipur to Agra Cab", url: "https://gulaticab.com/jaipur-to-agra-cab/", pickup: "Jaipur", drop: "Agra" },
  { name: "Jaipur to Ayodhya Cab", url: "https://gulaticab.com/jaipur-to-ayodhya-cab/", pickup: "Jaipur", drop: "Ayodhya" },
  { name: "Jaipur to Bareilly Cab", url: "https://gulaticab.com/jaipur-to-bareilly-cab/", pickup: "Jaipur", drop: "Bareilly" },
  { name: "Jaipur to Dehradun Cab", url: "https://gulaticab.com/jaipur-to-dehradun-cab/", pickup: "Jaipur", drop: "Dehradun" },
  { name: "Jaipur to Delhi Cab", url: "https://gulaticab.com/jaipur-to-delhi-cab/", pickup: "Jaipur", drop: "Delhi" },
  { name: "Jaipur to Faridabad Cab", url: "https://gulaticab.com/jaipur-to-faridabad-cab/", pickup: "Jaipur", drop: "Faridabad" },
  { name: "Jaipur to Ghaziabad Cab", url: "https://gulaticab.com/jaipur-to-ghaziabad-cab/", pickup: "Jaipur", drop: "Ghaziabad" },
  { name: "Jaipur to Gurgaon Cab", url: "https://gulaticab.com/jaipur-to-gurgaon-cab/", pickup: "Jaipur", drop: "Gurgaon" },
  { name: "Jaipur to Haldawni Cab", url: "https://gulaticab.com/jaipur-to-haldawni-cab/", pickup: "Jaipur", drop: "Haldawni" },
  { name: "Jaipur to Haridwar Cab", url: "https://gulaticab.com/jaipur-to-haridwar-cab/", pickup: "Jaipur", drop: "Haridwar" },
  { name: "Jaipur to Kanpur Cab", url: "https://gulaticab.com/jaipur-to-kanpur-cab/", pickup: "Jaipur", drop: "Kanpur" },
  { name: "Jaipur to Lucknow Cab", url: "https://gulaticab.com/jaipur-to-lucknow-cab/", pickup: "Jaipur", drop: "Lucknow" },
  { name: "Jaipur to Mathura Cab", url: "https://gulaticab.com/jaipur-to-mathura-cab/", pickup: "Jaipur", drop: "Mathura" },
  { name: "Jaipur to Meerut Cab", url: "https://gulaticab.com/jaipur-to-meerut-cab/", pickup: "Jaipur", drop: "Meerut" },
  { name: "Jaipur to Moradabad Cab", url: "https://gulaticab.com/jaipur-to-moradabad-cab/", pickup: "Jaipur", drop: "Moradabad" },
  { name: "Jaipur to Nainital Cab", url: "https://gulaticab.com/jaipur-to-nainital-cab/", pickup: "Jaipur", drop: "Nainital" },
  { name: "Jaipur to Noida Cab", url: "https://gulaticab.com/jaipur-to-noida-cab/", pickup: "Jaipur", drop: "Noida" },
  { name: "Jaipur to Rishikesh Cab", url: "https://gulaticab.com/jaipur-to-rishikesh-cab/", pickup: "Jaipur", drop: "Rishikesh" },
  { name: "Jaipur to Vrindavan Cab", url: "https://gulaticab.com/jaipur-to-vrindavan-cab/", pickup: "Jaipur", drop: "Vrindavan" },
  { name: "Jaipur Tour", url: "https://gulaticab.com/jaipur-tour/", pickup: "Jaipur", drop: "Jaipur" },
  { name: "Vrindavan to Noida Cab", url: "https://gulaticab.com/vrindavan-to-noida-cab/", pickup: "Vrindavan", drop: "Noida" },
  { name: "Vrindavan to Ramnagar Cab", url: "https://gulaticab.com/vrindavan-to-ramnagar-cab/", pickup: "Vrindavan", drop: "Ramnagar" },
  { name: "Vrindavan to Roorkee Cab", url: "https://gulaticab.com/vrindavan-to-roorkee-cab/", pickup: "Vrindavan", drop: "Roorkee" }
  ];
  